source 'https://rubygems.org'

gem 'selenium-webdriver'
gem 'cucumber'
gem 'page-object'
gem 'rspec'
gem 'pry'
gem 'pry-byebug'
gem 'httparty'
gem 'eyes_selenium'
gem 'gmail'
gem 'net-ssh'
gem 'hipchat'
gem 'jenkins_api_client'